### PR TITLE
Package Structure

### PR DESCRIPTION
**Pull request by DavZim**
Awesome idea and really useful for classes that I teach.
I thought a package structure might be helpful, so I implemented one.
Although spread/gather is not yet implemented, this branch has a slightly different, yet powerful api as it allows the user to specify different datasets as well as the by-argument for joins.

One downside though is that the extra-joins (where multiple observations of y are added) are not yet correctly implemented. 

Do you think this will be helpful?

To give you a brief overview:

``` r
library(tidyAnimatedVerbs)
#> Loading required package: tidyverse
#> Loading required package: gganimate
#> 
#> Attaching package: 'tidyAnimatedVerbs'
#> The following object is masked from 'package:dplyr':
#> 
#>     combine

singer <- data_frame(name = c("Mick", "John", "Paul", "Matthew", "Mick"),
                     band = c("Stones", "Beatles", "Beatles", "Muse", "Foreigner"),
                     age  = c(75, 40, 76, 40, 73))

instr <- data_frame(name = c("Mick", "John", "Mick", "Keith"),
                    band = c("Stones", "Beatles", "Foreigner", "Stones"),
                    plays = c("guitar", "bass", "guitar", "guitar"))

singer
#> # A tibble: 5 x 3
#>   name    band        age
#>   <chr>   <chr>     <dbl>
#> 1 Mick    Stones       75
#> 2 John    Beatles      40
#> 3 Paul    Beatles      76
#> 4 Matthew Muse         40
#> 5 Mick    Foreigner    73

instr
#> # A tibble: 4 x 3
#>   name  band      plays 
#>   <chr> <chr>     <chr> 
#> 1 Mick  Stones    guitar
#> 2 John  Beatles   bass  
#> 3 Mick  Foreigner guitar
#> 4 Keith Stones    guitar

animate_left_join(singer, instr, by = c("name", "band"), text_size = 5)
```

Created on 2018-08-22 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

### CODE REVIEW

**Comment by DavZim** [comment]
One small update: joins with extra rows are now fully supported.
Also the user can tweak the plots easier:
``` r
library(tidyAnimatedVerbs)
#> Loading required package: tidyverse
#> Loading required package: gganimate

singer <- data_frame(name = c("Mick", "John", "Paul", "Matthew", "Mick"),
                     band = c("Stones", "Beatles", "Beatles", "Muse", "Foreigner"),
                     age  = c(75, 40, 76, 40, 73))

instr <- data_frame(name = c("Mick", "John", "Mick", "Keith"),
                    band = c("Stones", "Beatles", "Foreigner", "Stones"),
                    plays = c("guitar", "bass", "guitar", "guitar"))

singer <- singer %>% slice(c(1:3, 1, 5))
instr <- instr %>% slice(c(1, 1:3))

singer
#> # A tibble: 5 x 3
#>   name  band        age
#>   <chr> <chr>     <dbl>
#> 1 Mick  Stones       75
#> 2 John  Beatles      40
#> 3 Paul  Beatles      76
#> 4 Mick  Stones       75
#> 5 Mick  Foreigner    73
instr
#> # A tibble: 4 x 3
#>   name  band      plays 
#>   <chr> <chr>     <chr> 
#> 1 Mick  Stones    guitar
#> 2 Mick  Stones    guitar
#> 3 John  Beatles   bass  
#> 4 Mick  Foreigner guitar

animate_left_join(
  singer, instr, by = c("name", "band"), 
  text_size = 5,
  text_family = "LM Roman 10",
  title_size = 15,
  title_family = "LM Roman 10",
  color_fun = viridis::magma,
  color_other = "#decbe4",
  color_header = "#525252"
)
```



Created on 2018-08-22 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by gadenbuie** [comment]
Wow, @DavZim! I'm really impressed by the amount of work you put into this! I normally do my work inside a package structure, but I didn't think there would be a need this time. Thank you for proving me wrong! :smile:

I really like that the user can now specify arbitrary data frames to animate and the number of parameters that can be tweaked in the plot output. There are a few places where I animated the operations using three key frames that I like a little more, but I think it's a reasonable trade-off for the ability to easily change the input data.

How would you like to work together? I like the direction and think a package structure is a good idea, so we definitely agree there. I'm happy to dig into the code whenever you're ready, but I don't want to get in your way if you're actively working on it still. As far as working together, I'm happy with anything from taking over completely when you're done (or tired of working on this) through letting you take the lead and providing input via code review. Just let me know what you'd like.

As some quick thoughts overall:

1. Would it be possible to parameterize the inclusion of the column headers? I think in certain cases it looks better without them.

1. There's some cleaning up to do around the use of `...` to make sure that they are used or that the additional arguments are passed to the right functions. It seems like `animate_join()` passes `...` to multiple functions and we might need to make sure the extra arguments end up in the right place.

    You can also use `#' @inheritDotParams <function name>` to automatically generate documentation for those parameters (in place of `#' @param ... passed to <function>`).

1. There are a few references to `base_plot()` in the documentation that I think should be `static_plot()`.

**Comment by gadenbuie** [comment]
Oh and definitely at a minimum can you update the DESCRIPTION to include your information?

**Comment by DavZim** [comment]
Glad that you like it :)

True, the three-piece movement makes understanding the operation easier. I think that could be implemented at one point.
For now, I would try to finish the gather/spread functionality, then I think we can try to merge the branches or at least go into more detail with code review etc.
Given that its night over here (Europe), I think I will try to finish that tomorrow.

My goal is to also supply basic information for something like filter, mutate, summarise, group-by mutate & summarise, and maybe separate and unite. And maybe in the longer run a small shiny app that the user can see the functionality with different datasets for different cases (i.e., the extra matches in joins).
That would make it a lot easier for me to teach dplyr/tidyverse-functionality.

Regarding your points: the ellipsis was more of a brute force approach than precision, so we should try to clean that for sure :D 
I haven't used ellipsis too much, therefore I am unsure what exactly to do. Once this branch is up to date we can go into this.

Overall, I am definitely happy to work together. Again, right now I would like to finish the background for the gather/spread functionality, then we can move forward together. 
Looking forward to it!

Best, 
David

**Comment by DavZim** [comment]
I've added the animate_gather and animate_spread functions.

I think we can try to move it forward by merging the branches. Also, if you find some time you can change/update the code.

One of the biggest issues right now is that the new animate tidy functions do not pass the ellipsis through.


``` r

library(tidyAnimatedVerbs)
#> Loading required package: tidyverse
#> Loading required package: gganimate
long <- data_frame(
  year = c(2010, 2011, 2010, 2011, 2010, 2011),
  person = c("Alice", "Alice", "Bob", "Bob", "Charlie", "Charlie"),
  sales = c(105, 110, 100, 97, 90, 95)
)
wide <- data_frame(
  year = 2010:2011,
  Alice = c(105, 110),
  Bob = c(100, 97),
  Charlie = c(90, 95)
)

animate_spread(long, key = "person", value = "sales")
```



Created on 2018-08-23 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by gadenbuie** [comment]
Very cool! I love how slightly different approaches to laying out the animation and movement lead to complimentary visualizations of the process. Like how we ended up with two similar animations for spread/gather but that are also different in a way that highlights different parts of the action.

I think it would be good to take a small step back and look at the overall structure. I'm interested to see what you think, but for me the three key steps to solve for these types of animations is

1. The layout of the data at each key frame
    - In part this is specific to the animated function (i.e. `left_join()` vs `right_join()`
    - On the other hand, the process of laying out a data frame for ggplot is the same except for translations in the x or y dimensions
2. Adding extra elements to key frames so that all objects are tracked throughout the animation (e.g. move to the right place)
3. Tweaking the plot or animation output (e.g. tweaking enter/exit behavior, `ease_aes()` or plot labels)

From a quick look through the code it seems like we're headed in this direction although maybe not completely there. I think that one of the benefits of making this a package rather than a collection of "hand-crafted" scripts is that we can add an additional layer of abstraction that will make it easier to build out more animations (for things like filter, mutate, etc.).

It's hard to tell from looking at the GitHub diffs (hoping to pull the code and dig in soon), but how much overlap is there between underlying functions among the "joins", "sets" and "gather/spread" animations? To be more concrete, which functions would you use to build a new animation in a different class (say filtering)? Is there a function that handles the core of step 2, or is this logic different for each animation group?

As a final question, if you could quickly describe the package layout as it is now, that would be very helpful to orient me as I dive in.

Thanks again!

**Comment by DavZim** [comment]
The underlying structure is definitely something that we need to think about.
My general goal was to first process the data using `processing_long` or `processing_wide`, or the `process_join` function for sets/joins.
These functions spit out a data.frame containing all the relevant information. That is the `.x`, `.y` values for plotting, colors, ids, etc. (a nice gimmick is that the processed data can be immediately plotted using `static_plot`).
I would love to cut the number of preprocessors but didn't find a solution yet.
The major issue is here that we need to be able to id each element of a plot (best in a standardised way). I tried this using the variables `.id_map` (linking in a spread/gather function to the id, i.e., year in the example) and `.key_map` (linking to the respective key), as well as the element type in `.type`. But I feel this is hard to generalize for different data structures. 
The outputs are then used in the higher functions `animate_join`/`animate_set` or `gather_spread`, where the movement is coordinated. 
A basic Minimum Working Example is provided here: https://gist.github.com/DavZim/2e829ae24b2e272c409899e01d420479

All joins/sets are done in a single movement, whereas the gather/spread functions take multiple steps (for each key-value one to be precise, plus initial and final states) if `detailed = TRUE` in `animate_gather/spread`. This handling is done in the `gather_spread` helper function.

To summarise:
The user can call `animate_*` functions that all take more or less the same inputs (depending on the function it may take a `by` argument or `keys/values`). 
The idea is to have data-processors (specific to the different type of function, joins+sets, long, and wide format) that transform the data into a standard format. Then we have a `move_together` function for the joins or use the `gather_spread` function for gather/spread that handle the movement of the tiles.
Colorings are done in `add_color_join/tidyr`.

To answer your question, all functions have a similar structure, but are not (yet?) interchangeable. For a new function (say group_by + summarise), one would need to specify a process-function that converts the input data into the processed form (with plotting information and all), and a second function that then specifies how the different steps (from input (or lhs) to output (rhs)) are displayed. If we find a unifying approach, that would be awesome.

Drawbacks/stuff to improve.
I think I was a bit sloppy at designing the structure of the processed data, i.e., the data from joins/tidyr looks quite different to me now, and sometimes it needs to have multiple entries so that entries do not disappear, this is something that we could improve using nested data-frames, where we save the idea.

Ellipsis `...` are not carefully done as you mentioned earlier. Currently the tidyr-functions do not pass them on at all...
closely related: the ... arguments in animate_gather are not fully working (working for one case at least). In the future this should work as well `animate_gather(wide2, key = "person", value = "sales", -year, -region)` or `animate_gather(wide2, key = "person", value = "sales", -year:region)`

**Comment by DavZim** [comment]
Also a minor thing: I didnt figure out how to make the output for the tidyr-functions as pretty as yours/as the joins...

**Comment by gadenbuie** [comment]
@DavZim Holding off on merging for now in case you have few more updates to push. Let me know when this is ready to merge into a `pkg` branch (see #12)

**Comment by DavZim** [comment]
I think you can merge as I don't have any updates currently. bind_cols and bind_rows prove to be a bit more complicated to integrate them into the join-family. It might be easier to write new functions.

**Comment by gadenbuie** [comment]
@DavZim Okay, I merged this pretty much as-is into the [pkg branch](https://github.com/gadenbuie/tidy-animated-verbs/tree/pkg).

The biggest thing I changed was [not depending on the tidyverse](https://www.tidyverse.org/articles/2018/06/tidyverse-not-for-packages/) and starting to think about global imports.

This probably broke the package, but mostly because we need to add the package name qualifiers to non-imported packages. Anywhere that the code breaks for this reason should require a qualifier. E.g. `gather(df, key, val)` will need `tidyr::` added. 

Also I didn't add `stringr` to Imports so that we can remember to replace those functions with base R, until that's fixed we can just `library(stringr)` around it.

**Pull request closed without merging**
