### PR TITLE
Add tidyr::pivot_*() animations

### LINKED ISSUE #27: tidyr :: pivot_wider() and pivot_longer()
Animation request for pivot_wider() and pivot_longer().

Background: “Pivotting” which converts between long and wide forms. tidyr 1.0.0 introduces pivot_longer() and pivot_wider(), replacing the older spread() and gather() functions. See vignette("pivot") for more details.

Link: https://tidyr.tidyverse.org/

### PR DESCRIPTION
**Pull request by LukasWallrich**
Thanks for your wonderful package. Like @kelseygonzalez, I use some of your great animations in my teaching, and was now looking for a way to introduce the new pivot_ functions. Therefore, I gave #27 another go, and think that I have resolved it in a way that addresses the issues that remained in #30. Please let me know if you would like me to add this to the README.

Fixes #27
Closes #30

### CODE REVIEW

**Comment by kelseygonzalez** [comment]
Fantastic job solving the errors I ran into @LukasWallrich ! Hopefully we can get this updated soon.

**Comment by gadenbuie** [comment]
Thank you very much @LukasWallrich (and @kelseygonzalez and everyone else who has worked on a pivot animation). Coming back to this repo I'm wishing I had used renv or targets or some other project and package management system (which may not have even existed back when I started this). I just finished setting that up and I'll be merging the changes in here shortly. Thanks for your patients figuring out the system I used and for putting the animations together!

**Comment by gadenbuie** [comment]
Okay, I spent quite a bit of time (like almost enough time to wonder if I'd be better off learning AfterEffects or figuring out how to do stop-motion animation) working with the pivot_wider/longer animation and I've ended up with the following draft.

What do you all think? Still need to add the animation into the Rmd-driven build system (README.Rmd) and then this will be ready to merge.

animated pivot_wider() and pivot_longer() explanation, made with a stylized data frame featuring colorful boxes that snap between wide and long forms

btw I really wanted to use ggtext to soften the `pivot_longer(wide` line rather than hiding it to draw focus to the `cols`, `names_to` and `values_to` arguments, but ggtext wouldn't preserve the horizontal alignment of the title text. Unfortunately it wasn't even in the realm of not perfect but livable.

I also spent approximately forever trying to get the title to line up correctly with the current state of the animation — i.e. start with **wide**, then **pivot_longer()**, etc. The frustration was epic and it took me roughly a dozen tries to find a reprex and then "solve" the "issue". Only to realize, now that I've uploaded the file, that it must be something specific about how the gif is encoded (i.e. the worst kind of problem) because the playback I see in this issue preview is **not at all** what I see when previewing the gif locally on my machine. I was able to get more consistent performance using the `magick_renderer()`, but it also created larger but lower quality files than gifksi (i.e. the worst kind of trade-off). Not sure where to go from here on that one.

**Comment by gadenbuie** [comment]
Regarding the last point, if I add the `{frame} - ` number into the title, I get consistent results that are always exactly what I want (minus the part where the frame appears in the title). Taking the frame number out of the title — but still giving each frame an individual title — somehow causes the gif to choose randomly which title to use for the pause between transitions.

tidyr-pivoting

**Comment by gadenbuie** [comment]
Okay I think I've finally worked out how to fix the jumpy title.


animated pivot_wider() and pivot_longer() explanation, made with a stylized data frame featuring colorful boxes that snap between wide and long forms

**Review by gadenbuie — APPROVED** [review]
Thank you @LukasWallrich and @kelseygonzalez!

I think this is in a good place now and I'm going to merge the PR, but please feel free to leave any comments either here or in a new issue if you spot anything I missed.

**Comment by LukasWallrich** [comment]
This looks great, thanks for all your work!

Personally, I love the visualisation of key and val, but find it confusing
when pivot_longer disappears - just because it is no longer clear what that
(incomplete) title means ... but others might find it helpful.

**Comment by kelseygonzalez** [comment]
Thanks for coming back to this @gadenbuie after a long break and fixing up the viz! I'm glad we got a MVP up for everyone who'd like to use it 🙌

**Comment by gadenbuie** [comment]
Thanks y'all. I'll add the complete `pivot_longer()` code back to the intermediate step

**Pull request merged**
