### PR TITLE
Added set operations

### PR DESCRIPTION
**Pull request by TylerGrantSmith**
I think what you did here is awesome and I saw a request on twitter to add additional set operations.  I figured it would be a good opportunity to finally learn about `gganimate`.  I tried to follow your style.

### CODE REVIEW

**Comment by gadenbuie** [comment]
Very cool, thanks a ton! Hopefully my style wasn't too obtuse :) I'm looking forward to reviewing/merging this this weekend or early next week.

Also, just want to make sure you're okay with the CC0 (images) and MIT (code) licenses.

**Comment by gadenbuie** [comment]
Just took a quick look at the animations in the rich diff and THESE ARE AWESOME!!!

**Comment by gadenbuie** [comment]
Thanks again @TylerGrantSmith for submitting this PR and for all of your work! I really appreciate it!

I've merged the changes into a new branch (see PR #6) so that I can add some changes as I'm refactoring the code a bit.

Just FYI for your future reference, when you're [creating a pull request](https://help.github.com/articles/creating-a-pull-request/), it's best to push your code to a new branch _in your repo_ and then submit the PR from that branch. That way you can use the `master` branch in your repo to stay up-to-date with the `master` branch in my repo. If you want to update your GitHub fork after I merge these changes into my master branch, it's probably easiest to just delete your fork and [create a new one](https://github.com/gadenbuie/tidy-animated-verbs/fork).

**Comment by TylerGrantSmith** [comment]
Great, glad you could use it @gadenbuie !  Thank you for the tips--this was my first attempt and really didn't have much of an idea what I was doing.

**Comment by gadenbuie** [comment]
No worries! The PR was great and thanks for being so thorough -- like adding to the README and everything else.

The only "big" thing that I changed was to change the row values from `[(x1, y1), (x2, y2)]` to `[(1, a), (2, b)]`, etc. I think it makes it a little easier to understand.

I also refactored the prep code quite a bit to incorporate the row-wise color scheme (which was a great idea, btw!) rather than have a separate `proc_data2()` function.

Do you have a twitter handle? I'm going to tweet these out later today and I'd like to include you in that if you want.

**Pull request closed without merging**
